### ISSUE TITLE
package.json for each assignment

### ISSUE THREAD

**Issue by karuppiah7890** [exercism/xecmascript#227]
Why keep a package.json file inside each assignment directory? This way I have to install the dependencies each time. I feel you could keep package.json inside the ecmascript folder

![issue](https://cloud.githubusercontent.com/assets/12808424/15402683/1da02478-1e13-11e6-943d-1c44965a4391.png)

**Comment by rchavarria** [comment]
Yep, you're right. It's a bit messy. And it's causing some problems, becuase each exercise has its own dependencies, but, the way it works (we implemented it), forces us to use the same `package.json` for all exercises. There is a issue to work on this (#84), but I didn't have time to think deeply about it.

Each exercise is supposed to be independent from each other. And, when a exercism.io user fetches an exercise, the platform should provide her all files necessary to run the tests.

There is a `package.json` file on each exercise directory to keep each exercise as independent as possible. One solution could be to force users to install all those tools (Babel, Jasmine, Gulp, ESLint,..) globally with `npm -g`. In my opinion, forcing users to do so is not a good idea.

I hope this answers your question. If you have some ideas to improve this, feel free to comment them. I'd love to have some discussions about this.

**Comment by karuppiah7890** [comment]
I didn't get the part about "forces us to use the same ```package.json``` for all exercises"

And yeah, I get it that you want to keep the exercises independent. So that, people can download them independently and only the exercises they want and may be skip others. And yeah, I will look upon this - I still don't know about the testing files and what other modules are present in the dependencies and the working. Once I understand the working, I will discuss on this :) And yeah, I did see that issue (#84) but couldn't understand much. And was confused. So I put this up.

**Comment by rchavarria** [comment]
> forces us to use the same `package.json` for all exercises

At the beginning, with just two or three exercises, it was ok to have several `package.json` files, unconnected files. But when the track started to grow, and one needed to change lots of files in the same way, we came up with a solution: just have a main `package.json` on the root folder, and propagate with a script the changes to all exercises. 

It's not the ideal solution, and it's the reason behind #84.

I you don't mind, I'm going to close this issue. Feel free to reopen it you miss something.
Thanks for your words.
